# Generated by Django 5.2.5 on 2025-08-17 23:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_number', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BankAccount',
                'indexes': [models.Index(fields=['balance'], name='BankAccount_balance_ac03a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_account_balance_gte_zero')],
            },
        ),
    ]
