# Generated by Django 5.2.5 on 2025-08-18 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('transaction_type', models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bankaccount.bankaccount')),
            ],
            options={
                'db_table': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
